/**
 * Curated brand allowlist — Giftr only surfaces products from these brands.
 * Names are matched case-insensitively (see `normalizeBrandName`) against
 * `Product.brands[].name` / `Brand.name` from the Channel3 catalog.
 */
export const ALLOWED_BRAND_NAMES: readonly string[] = [
  "'47",
  "& Other Stories",
  "&Daughter",
  "14th Night",
  "16ARLINGTON",
  "3.1 Phillip Lim",
  "4th & Reckless",
  "5 SENS",
  "8 Other Reasons",
  "87Origins",
  "A.L.C",
  "ABADIA",
  "Abbey Glass",
  "Abbode",
  "Abercrombie & Fitch",
  "Abigails",
  "Acler",
  "Acne Studios",
  "Acqua di Parma",
  "Addison Ross",
  "adidas",
  "Adina Eden",
  "Adina Reyter",
  "Adriana Degreas",
  "AERIN",
  "Aerin Lauder",
  "Aesop",
  "Aesther Ekme",
  "aeyde",
  "Aflalo",
  "AFRM",
  "AG1",
  "AGOLDE",
  "Agua Bendita",
  "Agua By Agua Bendita",
  "Aidan Mattox",
  "Aimee Kestenberg",
  "Aje",
  "Aje.",
  "Akoia Swim",
  "Alaïa",
  "Alanui",
  "Alberta Ferretti",
  "Alejandra Alonso Rojas",
  "ALEKKA",
  "ALÉMAIS",
  "Alessandra Rich",
  "Alex Mill",
  "Alexandra Pijut",
  "Alexandre Birman",
  "Alexia María",
  "Alexis",
  "Alexis Bittar",
  "alice",
  "alice + olivia",
  "Alice and Olivia",
  "Alice Lane Home Collection",
  "ALIGNE",
  "aligrace",
  "Aline Coquelle",
  "Alison Lou",
  "All The Ways",
  "All-Clad",
  "AllSaints",
  "Allude",
  "Alo",
  "Alo Yoga",
  "Altuzarra",
  "ALV Jewels",
  "Amanda Uprichard",
  "Amazon",
  "American Eagle",
  "American Vintage",
  "Amina Muaddi",
  "AMUR",
  "Amy Astley",
  "Ana Luisa",
  "Ana Radu",
  "Ancient Greek Sandals",
  "ANDERSONS",
  "Andie Swim",
  "Andrea Gomez",
  "Andrea Iyamah",
  "Andres Otalora",
  "ANEMOS",
  "ANFISA Skin",
  "ANINE BING",
  "ANJA Paris",
  "Ann Mashburn",
  "Ann Taylor",
  "Anna + Nina",
  "Anna Cate",
  "Anna October",
  "ANNA QUAN",
  "Anthropologie",
  "Antonio Melani",
  "Anya Hindmarch",
  "APIECE APART",
  "Apilco",
  "APL - Athletic Propulsion Labs",
  "APPARIS",
  "Apple",
  "AQUA",
  "Aquazzura",
  "ARAKII",
  "Araks",
  "Arcina Ori",
  "Arianne Elmy",
  "Ariel Gordon Jewelry",
  "Ariel Okin",
  "Aritzia",
  "Ark Swimwear",
  "ARKET",
  "Armand Limnander",
  "ARMANI",
  "Armitron",
  "Arotagas",
  "Art Life Practice",
  "Artifact Uprising",
  "Artless Forever",
  "ASHA by Ashley McCormick",
  "AshleyStambouli",
  "ASOS",
  "Aspinal of London",
  "Assouline",
  "ASTA RESORT",
  "Astier de Villatte",
  "ASTR the Label",
  "Athleta",
  "ATP Atelier",
  "Atu Body Couture",
  "Audry Rose",
  "Augustinus Bader",
  "Aurate",
  "Aurate New York",
  "AUREUM",
  "Avaline",
  "Aviator Nation",
  "Away",
  "Aya Muse",
  "AYR",
  "Azeeza",
  "ba&sh",
  "Babaton",
  "Babiators",
  "Baby Gold",
  "Badgley Mischka",
  "BAEO",
  "Bailey Rose",
  "Ballerina Farm",
  "Banana Republic",
  "Banana Republic Factory",
  "Bandier",
  "Banjanan",
  "Banwood",
  "BAOBAB",
  "Barbara Tfank",
  "Barbour",
  "Bardot",
  "Bathing Culture",
  "Bauble Stockings",
  "BaubleBar",
  "BAUM UND PFERDGARTEN",
  "BDG",
  "Beatriz Ball",
  "Beauty Pie",
  "BEC + BRIDGE",
  "BedHead PJs",
  "Bembien",
  "Ben-Amun",
  "Bergdorf Goodman",
  "BERNADETTE",
  "Bey-Berk",
  "BHLDN",
  "Billini",
  "Biodance",
  "Black Door Studio",
  "Black Suede Studio",
  "BLANKNYC",
  "Bleu de Chauffe",
  "Blossom and Pear",
  "Blumarine",
  "BOB & BLOSSOM",
  "Bobbi Brown Cosmetics",
  "Boden",
  "Bodum",
  "Bogner",
  "Bombas",
  "BonBonNYC",
  "BONDI BORN",
  "Bordallo Pinheiro",
  "Borgo de Nor",
  "Bose",
  "Bottega Veneta",
  "Bougie Gougies LLC",
  "Boy Smells",
  "Bragagnolo Argenti",
  "Brandon Maxwell",
  "Brightland",
  "Brinker + Eliza",
  "Britt Netta",
  "Brixton Pottery",
  "Brooke & Lou",
  "Brooklinen",
  "Brooklyn Candle Studio",
  "Brother Vellies",
  "Brunch",
  "Burberry",
  "Bvlgari",
  "By Anthropologie",
  "BY MALENE BIRGER",
  "By Watters",
  "Byredo",
  "CAARA",
  "Cabana",
  "Cabana Magazine",
  "Caitlin Wilson",
  "Cala de la Cruz",
  "Call It By Your Name",
  "Camila Coelho Collection",
  "Camp Snap",
  "Cann",
  "CANO",
  "Cap d'Antibes",
  "Cara Cara",
  "Caraway",
  "Caraway Home",
  "Carbon & Hyde",
  "CARELLI",
  "Carine Gilson",
  "Carl Friedrik",
  "CARMEN SAYS",
  "Carolina Amato",
  "Carolina Herrera",
  "Carolina Irving and Daughters",
  "Carolina K",
  "CAROLINE CONSTAS",
  "Cartier",
  "Cartolina",
  "Casa Bombón",
  "Casa Clara",
  "Casa Hermana",
  "Castañer",
  "Caudalie",
  "CB2",
  "Ceae Shop",
  "Celia B",
  "Celine",
  "Celine Eyewear",
  "Cendre",
  "Cesta Collective",
  "Chamberlain Coffee",
  "Chan Luu",
  "CHANEL",
  "ChappyWrap",
  "Charbonnel Et Walker",
  "Charlotte Tilbury",
  "Charo Ruiz",
  "Chef’s Mandala",
  "Chefanie",
  "Chimi",
  "Chimo",
  "Chloé",
  "Chloe Gosselin",
  "CHORD",
  "Chris McMillan",
  "Christian Louboutin",
  "Christine's",
  "CHRISTOFLE",
  "Christopher Esber",
  "Ciao Lucia",
  "Cire Trudon",
  "Citizens of Humanity",
  "Clare V.",
  "Clé de Peau Beauté",
  "CLEA",
  "Clinique",
  "Clio Peppiatt",
  "Coco Shop",
  "Cody Foster",
  "Cody Foster & Co",
  "Cole Haan",
  "Colores Collective",
  "Commence",
  "Commense",
  "Common Projects",
  "Compartés",
  "Comrad",
  "Coperni",
  "Corbell Silver",
  "Corpus",
  "COS",
  "Cosi Tabellini",
  "Costarellos",
  "Couper",
  "Crate & Barrel",
  "CRISTALLINI",
  "Cristiano Marcheli",
  "Cristina Re",
  "Crow Canyon Home",
  "Crown Affair",
  "Cult Gaia",
  "Cumulus",
  "CurrentBody",
  "Cuyana",
  "CYK Caviar",
  "Damaris Bailey",
  "DAMDAM",
  "Damson Madder",
  "Danarys",
  "danarys New York",
  "Dandelion Chocolate",
  "Danielle Frankel",
  "David Cannon",
  "David Yurman",
  "De Castro",
  "De La Vali",
  "De Loreta",
  "De Loreta x Couper",
  "Dean Davidson",
  "Dear Annabelle",
  "Deborah Pagani",
  "Dehanche",
  "Delfi Collective",
  "Delphine",
  "Deme by Gabriella",
  "DeMellier",
  "DES_PHEMMES",
  "Design Leadership Network",
  "Desmond & Dempsey",
  "DESTREE",
  "Diane von Furstenberg",
  "DIARRABLU",
  "Dima Ayad",
  "Dior",
  "Diptyque",
  "Diptyque Paris",
  "DISSH",
  "DITA Eyewear",
  "Divi",
  "DL1961",
  "DÔEN",
  "Dolce & Gabbana",
  "Dolce Leone Swim",
  "Dolce Vita",
  "DONNI.",
  "Dorothee Schumacher",
  "Dorsey",
  "Dower & Hall",
  "Dr. Barbara Sturm",
  "Dr. Dennis Gross",
  "Dr. Diamond's Metacine",
  "DR. MARNIE",
  "Dragon",
  "Dragon Diffusion",
  "Dress The Population",
  "Dries Van Noten",
  "drinkag1.com",
  "Ducie",
  "Dyson",
  "EarlyBird CBD",
  "EAVES",
  "Eberjey",
  "EBY",
  "EDDY",
  "Edie Parker",
  "EF Collection",
  "Electric Picks",
  "ELEMIS",
  "ELIE SAAB",
  "Elisa Johnson",
  "Eliya The Label",
  "Elizabeth Lake",
  "Elleme",
  "ELLIATT",
  "Ellsworth + Ivey",
  "Elm Biosciences",
  "EltaMD",
  "Emi Jay",
  "Emilia Wickstead",
  "Emme Parsons",
  "Empire Cake",
  "Emporio Sirenuse",
  "En Saison",
  "Endless Rose",
  "English Factory",
  "Enrico Bernardo",
  "Enza Costa",
  "Epsom-It",
  "Erdem",
  "Eres",
  "Eric Buterbaugh",
  "Eriness Jewelry",
  "ESCVDO",
  "Especia",
  "Esse Studios",
  "Essentiel Antwerp",
  "Estelle Colored Glass",
  "ESTOUBLON",
  "ET OCHS",
  "ETOILE",
  "Etro",
  "Ettika",
  "etúHOME",
  "Evereve",
  "Everlane",
  "Everyone Loves The Weekend",
  "Facettes Studio",
  "FAITHFULL",
  "Fallon & Ava",
  "Fanm Mon",
  "FARM Rio",
  "Favorite Daughter",
  "Fazeek",
  "Fe Noel",
  "Ferragamo",
  "Fewer Finer",
  "Fiametta",
  "Fieldbar",
  "Figue",
  "Finding Ferdinand",
  "Fishwife",
  "Flabelus",
  "Flamingo Estate",
  "Flattered",
  "Fleur du Mal",
  "Flora Nikrooz",
  "Florence & Fortitude",
  "FLOWERBX",
  "Flying Sheep Country",
  "Follow Suit",
  "Fornasetti",
  "FRAME",
  "Francesca Miranda",
  "Frankies Bikinis",
  "FRÉ Skincare",
  "Fred Leighton",
  "FRĒDA SALVADOR",
  "Free People",
  "fresh",
  "Frette",
  "freya.",
  "FREYRS Eyewear",
  "FUNBOY",
  "Fur",
  "Furbish",
  "Furbish Studio",
  "G.H.BASS",
  "Gabriela Hearst",
  "Galvan",
  "GANNI",
  "GAP",
  "Garrett Leight",
  "Garrett Popcorn",
  "Gathre",
  "Generation Love",
  "Georgia Hardinge",
  "Giambattista Valli",
  "Gianvito Rossi",
  "Gigi Burris",
  "Ginori 1735",
  "Gisou",
  "Givenchy",
  "Glossier",
  "Glow Recipe",
  "Gohar World",
  "Golden Rabbit",
  "Goldie Tees",
  "Good American",
  "GoodOnya",
  "goop",
  "goop Beauty",
  "Gooseberry Intimates",
  "gorjana",
  "Graphic Image",
  "Greta Constantine",
  "Gucci",
  "GUERLAIN",
  "Guest in Residence",
  "Guizio",
  "Gül Hürgel",
  "GWYN",
  "h:ours",
  "H&M",
  "Haight",
  "Hair by Sam McKnight",
  "Halfpenny London",
  "Halston",
  "Hampton Water Wine",
  "Hanacure",
  "Hanky Panky",
  "Hannah Artwear",
  "hanni",
  "Happy Organics",
  "HART",
  "Hat Attack",
  "Hatch",
  "Havaianas",
  "Hearth & Hand with Magnolia",
  "Heather Taylor Home",
  "Heaven Mayhem",
  "Hedge Clothing",
  "Heimat Atlantica",
  "Heiress Beverly Hills",
  "HEIRLOME",
  "Helsa",
  "Helsi",
  "Hemant & Nandita",
  "HEMANT AND NANDITA",
  "Henne",
  "Henry Handwork",
  "Herend",
  "Hereu",
  "Heritage Metalworks",
  "Hermès",
  "Hevron",
  "Hill House Home",
  "Hodinkee",
  "HOKA",
  "Homebodii",
  "Hotel Lobby Candle",
  "HOUSE OF CB",
  "House of Dagmar",
  "House of Harlow 1960",
  "House of Zalo",
  "Hudson Grace",
  "Hudson Sutler",
  "HUGO",
  "Huishan Zhang",
  "Hunter Bell",
  "Hunting Season",
  "Hunza G",
  "HUTCH",
  "Hyacinth House",
  "Ian Shive",
  "Igloo-Store US",
  "ILA",
  "Illesteva",
  "INCOTEX",
  "Inez",
  "Inslee Fariss",
  "Intimately",
  "Intimissimi",
  "Inuikii",
  "iota",
  "Irene Neuwirth",
  "Isabel Marant",
  "Isla & White",
  "Issy Granger",
  "j. crew factory",
  "J. Mueser",
  "J.Crew",
  "J.Crew Factory",
  "J.McLaughlin",
  "Jack Black",
  "Jacquemus",
  "Jacquie Aiche",
  "James Perse",
  "Janessa Leoné",
  "Jarosinski & Vaugoin",
  "Jaxon Lane",
  "Jay McInerney",
  "Jaymes Paper",
  "Jeffrey Campbell",
  "Jenni Kayne",
  "Jennifer Behr",
  "Jennifer Fisher",
  "Jenny Packham",
  "Jenny Yoo",
  "Jessica McCormack",
  "JIA JIA",
  "Jil Sander",
  "Jimmy Choo",
  "Jimmy Fairly",
  "Jo Malone",
  "Joanna Vargas",
  "Joel Stein",
  "Johanna Ortiz",
  "Johnson Brothers China",
  "Johnstons of Elgin",
  "Jonathan Adler",
  "Jones Road Beauty",
  "Joslin",
  "Juan de Dios",
  "Judith Leiber Couture",
  "JULIETTA",
  "Juliska",
  "Jullist",
  "Juvia's Place",
  "JW PEI",
  "Kallmeyer",
  "Kamperett",
  "Kassatex",
  "Kat Burki Skincare",
  "Kate Ford",
  "Kate McLeod",
  "Kathy Kuo Home",
  "Katie May",
  "KAYALI",
  "Kayu",
  "Kemo Sabe",
  "Kerry McGauley",
  "KHAITE",
  "Kiehl's",
  "Kiel James Patrick",
  "Kika Vargas",
  "Kiki de Montparnasse",
  "Kilentar",
  "Kilian",
  "Kilte",
  "Kinderbrook",
  "KINDERBROOK HOME",
  "Kinn",
  "KIVARI",
  "Kleid",
  "Klimchi",
  "Koala Eco",
  "KORA Organics",
  "Kosas",
  "kourt",
  "KOZAKH",
  "KREWE",
  "KREWE Eyewear",
  "KUJTEN",
  "KULE",
  "L.CUPPINI",
  "L.L.Bean",
  "L'Academie",
  "L'AGENCE",
  "L'artisan Parfumeur",
  "L'IDÉE",
  "L'OBJET",
  "La Coqueta",
  "La DoubleJ",
  "La Fête Needlepoint",
  "LA FUORI",
  "La Gallina Matta",
  "La Ligne",
  "La Maregold",
  "La Mer",
  "La Veste",
  "Laboratorio Paravicini",
  "Lack of Color",
  "Läderach",
  "Läderach Chocolatier Suisse",
  "Ladurée",
  "LAFCO New York",
  "Laguiole",
  "LAKE",
  "Lake & Skye",
  "LAMARQUE",
  "Land of Mila",
  "Lands' End",
  "Laneige",
  "Lanvin",
  "LAPOINTE",
  "Larroudé",
  "Laundry Sauce",
  "Laura Cangussu",
  "Laure Verchère",
  "Lavoratti 1938",
  "Le Bop",
  "Le Creuset",
  "LE GOURMET CENTRAL",
  "Le Kasha",
  "Le Labo",
  "Le Lion",
  "Le Monde Béryl",
  "Le Niné",
  "Le Specs",
  "Le Tanneur",
  "Le Toy Van",
  "Leatherology",
  "LEAU",
  "Lee Mathews",
  "Leesa",
  "Left On Friday",
  "Lein",
  "Lela Rose",
  "Lemme",
  "Leo Lin",
  "Lesea Berry",
  "LESET",
  "Lettermade",
  "Levain Bakery US",
  "Levi's",
  "Levis",
  "Lia Burke Libaire",
  "Liberowe",
  "Lido Swimwear",
  "Lié Studio",
  "Liffner",
  "Liis",
  "Lily and Bean",
  "Lindquist",
  "Lindy Hemming",
  "Line & Dot",
  "Lineage Provisions",
  "Lingua Franca",
  "Lioness",
  "LISA YANG",
  "Little English",
  "Little Fancy Books",
  "Little Lies",
  "Little Liffner",
  "Little Remedies",
  "Liv Foster",
  "Lizzie Fortunato",
  "Loeffler Randall",
  "Loewe",
  "loewe perfumes",
  "Lolë US",
  "LoQ",
  "Loren Hope",
  "Loretta Caponi",
  "Lorna Murray",
  "Loro Piana",
  "Lotta Camilla Teale",
  "Louis Vuitton",
  "Louise",
  "Louise New York",
  "LouLou Baker",
  "Loulou de Saison",
  "LOULOU STUDIO",
  "Lovaan",
  "Lovers And Friends",
  "LoveShackFancy",
  "LPA",
  "LSA",
  "LSPACE",
  "Lu Goldie",
  "Lucy Paris",
  "Lug Von Siga",
  "Luisa Beccaria",
  "Lulla Collection",
  "lululemon",
  "Lunya",
  "Luv Aj",
  "Lycette Designs",
  "Lynen",
  "M.Gemi",
  "M.Marquise",
  "M&S",
  "Mac Duggal",
  "Machete",
  "Madewell",
  "MAE NEW YORK",
  "Maeve",
  "Magda Butrym",
  "Magnolia Bakery",
  "Maileg USA",
  "Maison Amory",
  "Maison Francis Kurkdjian",
  "Maison Louis Marie",
  "Maison Margiela",
  "Maison Marigold",
  "Maisonette",
  "Maje",
  "Manebi",
  "MANGO",
  "Mango Outlet",
  "Manito",
  "Manolo Blahnik",
  "Mansur Gavriel",
  "Mara Hoffman",
  "Marant Étoile",
  "Marc Le Bihan",
  "Marcella",
  "March Hare",
  "Mare Mare",
  "Margaux",
  "Maria de la Orden",
  "Marie Oliver",
  "Marina Moscone",
  "Marine Layer",
  "Mariposa",
  "Mark & Graham",
  "Mark and Graham",
  "Markarian",
  "Marlies Grace",
  "Marlo Laz",
  "Marmar Halim",
  "Marni",
  "Marques Almeida",
  "Marrakshi Life",
  "Marshall",
  "Marta Ferri",
  "Martine Buchet",
  "Marysia",
  "MATCH 1995",
  "Match South",
  "Material",
  "Maticevski",
  "Matouk",
  "Matteau",
  "Matthew Bell",
  "Max Mara",
  "Maygel Coronel",
  "McGee & Co.",
  "ME+EM",
  "MEIMEIJ",
  "Mejuri",
  "Melie Bianco",
  "Melinda Maria",
  "Melissa Odabash",
  "MERIT Beauty",
  "Merlette",
  "MESHKI",
  "Mestiza New York",
  "MG&Co.",
  "Mignonne Gavigan",
  "Miguelina",
  "MIKOH",
  "Milla",
  "Miller Collective",
  "MILLY",
  "Mimétique",
  "MINKPINK",
  "Minnie-Mae Studio",
  "minnow",
  "Miron Crosby",
  "Missoni",
  "Missoni Mare",
  "Mitzi by Hudson Valley Lighting",
  "Miu Miu",
  "MJ Tablescapes",
  "ML Monique Lhuillier",
  "Moda Domus",
  "Modern Citizen",
  "Modern Gem Co",
  "Molly Goddard",
  "Momofuku",
  "Mon Ami",
  "Moncler",
  "Monday",
  "Monday Body",
  "Monday Swimwear",
  "Monica Vinader",
  "Monique Lhuillier",
  "Monogram Mary",
  "Monrow",
  "Montblanc",
  "Montce",
  "Montsand",
  "Moon Boot",
  "Moon Juice",
  "Moon River",
  "More To Come",
  "Mosser Glass",
  "Mossighi",
  "MOTHER",
  "Mother Science",
  "MR P.",
  "Mr. P",
  "Mrs. Alice",
  "Muna",
  "Mushie",
  "MUTHA",
  "My Store",
  "MZ Wallace",
  "NAADAM",
  "Nadine Merabi",
  "Nancy Yang",
  "Narcisco Rodriguez",
  "Nata Concept Store",
  "Natalie Rockefeller",
  "National Geographic",
  "NATORI",
  "NBD",
  "Nécessaire",
  "Negative",
  "Neous",
  "Nette",
  "Never A Wallflower",
  "New Balance",
  "New York Puzzle Company",
  "Newey & Bloomer",
  "NIA",
  "Nicholas",
  "Nick Foulkes",
  "Nicola Bathie",
  "Nike",
  "NILI LOTAN",
  "Nina Ricci",
  "Nine Fair Backgammon",
  "No Makeup Makeup®",
  "No Pise La Grama",
  "No Reservations",
  "NOOD",
  "Nood Beauty",
  "Nookie",
  "Noon & Moon",
  "Nordstrom",
  "Nori",
  "Norma Kamali",
  "Nour Hammour",
  "Nutrafol",
  "nutribullet",
  "Nuxe",
  "o.p.t",
  "OchreLane",
  "Octavia Elizabeth",
  "Odisséi",
  "Officina Profumo Farmaceutica di Santa Maria Novella",
  "Officine Universelle Buly",
  "OhSevenDays",
  "OLAPLEX",
  "Old World Christmas",
  "Olga Berg",
  "Oliver Peoples",
  "Oliver Spencer",
  "Olivet",
  "Olivia von Halle",
  "Olympia Le-Tan",
  "ONE/OF",
  "OneSkin",
  "Onia",
  "Onward Reserve",
  "Open Edit",
  "Oribe",
  "Origins",
  "Oríré",
  "Orlebar Brown",
  "Oscar de la Renta",
  "OSEA",
  "Oséree",
  "ossa new york",
  "Ossou",
  "Ouai",
  "Our Place",
  "Oura",
  "Over The Moon",
  "Palm Noosa",
  "Pamela Munson",
  "PANGAIA",
  "Papier",
  "Parachute Home",
  "Paris Georgia",
  "PARIS/64",
  "Parker Thatch",
  "Pascal",
  "Patricia Green",
  "Patrick Ta",
  "Paul Arnhold Glass",
  "Paula's Choice",
  "Pêche",
  "Peixoto",
  "Pelican",
  "Penelope Chilvers",
  "Penny Linn",
  "Perfect Moment",
  "Peter Thomas Roth",
  "Petite Plume",
  "Philippa1970",
  "Philosophie",
  "Philosophy Di Lorenzo Serafini",
  "Phlur",
  "Picante",
  "Pink City Prints",
  "Pistola Denim",
  "Playa Lucila",
  "PMD Beauty",
  "PODYH",
  "Polène",
  "Polo Ralph Lauren",
  "Pomander Place",
  "Pomegranate",
  "Pomellato",
  "Poppie Toys",
  "PORTA",
  "POSSE",
  "Pottery Barn",
  "Pottery Barn Kids",
  "PQ Swim",
  "Prada",
  "Proenza Schouler",
  "ProLon",
  "Pucci",
  "Puka the Label",
  "Quay",
  "Queen Musia",
  "Queen of the Court Brand",
  "Quince",
  "Quincy Mae",
  "Rabanne",
  "Rachel Gilbert",
  "Rafe New York",
  "rag & bone",
  "Rails",
  "Raishma",
  "Ralph Lauren",
  "Raquel Diniz",
  "Rare Beauty",
  "Ray-Ban",
  "Raye",
  "Réalisation Par",
  "Rebecca Udall",
  "Rebecca Vallance",
  "Redken",
  "REDONDO BRAND",
  "Reed & Barton",
  "Reed Smythe & Company",
  "Reformation",
  "REFY Beauty",
  "Regime des Fleurs",
  "Remedy Skin",
  "Ren Vois",
  "RENDOLL",
  "REPETTO",
  "RESA",
  "Retrofete",
  "Revelry",
  "Revolve",
  "REVOLVE LOS ANGELES",
  "Rhode",
  "Rhode Skin",
  "Rhone",
  "Riedel",
  "Rigaud Paris",
  "RIMOWA",
  "Ring Concierge",
  "RIXO",
  "RMS Beauty",
  "Ro's Garden",
  "ROAME.",
  "ROARI",
  "Robert Williams",
  "Rodarte",
  "Roe",
  "Róhe",
  "Roksanda",
  "Roland Mouret",
  "Ronny Kobo",
  "RosewaterHouse",
  "Rosie Assoulin",
  "ROTATE Birger Christensen",
  "Rowie's Macarons",
  "Roxanne Assoulin",
  "Royal Copenhagen",
  "Royce New York",
  "RŌZ",
  "RRL",
  "RÙADH",
  "RUE de VERNUIL",
  "Rue Sophie",
  "Ruggable",
  "Rugs USA",
  "Runaway the Label",
  "Ruti",
  "Sabre Paris",
  "Sabre-Paris",
  "Sachin & Babi",
  "Safiyaa",
  "Sageandwildliving",
  "Saie",
  "Saint Jane",
  "SAINT LAURENT",
  "Sakara",
  "Salisbury",
  "Saloni",
  "SALT & STONE",
  "Sam Edelman",
  "SAME LOS ANGELES",
  "Sandro",
  "Sanoë",
  "Santa Maria Novella",
  "Sarah Flint",
  "SARDINE",
  "Sau Lee",
  "Saulė Label",
  "Savette",
  "SAYLOR",
  "Scalamandre",
  "Scandles",
  "Scanlan Theodore",
  "Schutz",
  "Scout & Nimble",
  "Sea",
  "Sea New York",
  "SELF PORTRAIT",
  "Self-Portrait",
  "Selima Optique",
  "Sensi Studio",
  "Sequin",
  "Serena & Lily",
  "SEROYA",
  "Seven Wonders",
  "Sézane",
  "SFERRA",
  "SG Fine",
  "Shane Carley",
  "Shani Shemer",
  "SharkNinja",
  "Sharland England",
  "SHASHI",
  "Shatha Essa",
  "Shinola",
  "Shona Joy",
  "Shoshanna",
  "Show Me Your Mumu",
  "Shushu/Tong",
  "SIEDRÉS",
  "Siegelman Stable",
  "Significant Other",
  "Silvia Tcherassi",
  "SIMKHAI",
  "SIMONMILLER",
  "Simplified",
  "SIN",
  "SIR",
  "SIR.",
  "SIRAPOP",
  "Sisley Paris",
  "Sissy Light",
  "Sister New York",
  "Skeem",
  "SkinCeuticals",
  "Sleeper",
  "SLVRLAKE",
  "Smeg",
  "Smith & Quinn",
  "Smythson",
  "SNDYS",
  "Soft Goat",
  "Soft Services",
  "Soho Home",
  "Solace London",
  "SOLD OUT NYC",
  "Soleia Lane",
  "Soleil Soleil",
  "Solid & Striped",
  "Sonya Moda",
  "Sophie Bille Brahe",
  "Sophie Lou Jacobsen",
  "SOSHE Beauty",
  "Spartina 449",
  "Spencer's",
  "Spinelli Kilcollin",
  "Splendid",
  "Sports Illustrated",
  "Sprezz",
  "ST. AGNI",
  "Stand Studio",
  "Starling",
  "Staub",
  "STAUD",
  "Stella & Dot",
  "Steve Madden",
  "Still Here",
  "Stone Cold Fox",
  "Stoney Clover Lane",
  "Streets Ahead",
  "Stuart Weitzman",
  "Studio Amelia",
  "Sugarfina",
  "Summer Fridays",
  "Sunday Best",
  "Sunday Riley",
  "SUNNYLiFE",
  "Super Smalls",
  "Supergoop!",
  "Sur La Table",
  "Surcie",
  "Susan Alexandra",
  "Susana Monaco",
  "Susanna Chow",
  "Susanne Kaufmann",
  "Sveva's Home",
  "Sweed Beauty",
  "Sydney Evan",
  "Sylvia Toledano",
  "Table Two Studio",
  "Tae Park",
  "Taller Marmo",
  "Tan-Luxe",
  "Tanya Taylor",
  "Tata Harper",
  "Tatcha",
  "tbh Skincare",
  "Te Neues Publishing Company",
  "Temperley London",
  "Tenoverten",
  "Teri Jon",
  "THATCH",
  "The Attico",
  "The Conran Shop",
  "The Dime Store",
  "The Elder Statesman",
  "The Favorites",
  "The Frankie Shop",
  "The Go-To",
  "THE GREAT.",
  "The Mrs. Box",
  "The New Arrivals by Ilkyaz Ozel",
  "The New Arrivals Ilkyaz Özel",
  "The Outset",
  "THE OWN STUDIO",
  "The Row",
  "The Six Bells",
  "The Skinny Confidential",
  "The Super Puff",
  "The Wolf Gang",
  "Themis Z",
  "Theory",
  "Therabody",
  "Thierry Colson",
  "Third Form",
  "Threshold",
  "Threshold designed with Studio McGee",
  "Throwing Doubles",
  "Tiffany & Co.",
  "TKEES",
  "Tom Beckbe",
  "Tom Ford",
  "Tony Bianco",
  "Tory Burch",
  "Tory Sport",
  "TOTEME",
  "Touchland",
  "TOVE",
  "Tower 28",
  "TRASK",
  "Tres J",
  "Tricia Lowenfield",
  "Trina Turk",
  "Tropic",
  "Trudon",
  "True Botanicals",
  "tuck shop",
  "Tuckernuck",
  "Tuckernuck Accessories",
  "Tuckernuck Home",
  "TUDOR",
  "TULA Skincare",
  "Tularosa",
  "TUMI",
  "tutto",
  "Two's Company",
  "TWP",
  "Tyler Ellis",
  "U Beauty",
  "Ugg",
  "Ulla Johnson",
  "Uncommon James",
  "Universal Thread",
  "UNTUCKit",
  "Urban Expressions",
  "Urban Outfitters",
  "Ursa Major",
  "V. Chapman",
  "Valentino",
  "Valentino Garavani",
  "VALÉRE",
  "Van Cleef & Arpels",
  "Varley",
  "Venus et Fleur",
  "VERAFIED",
  "Verandah",
  "Veronica Beard",
  "VERSED",
  "Viani Milano",
  "Vibi Venezia",
  "Victoria Beckham Beauty",
  "Villeroy & Boch",
  "vin.",
  "Vince",
  "Vintage - Unbranded",
  "VIO2 Mouth Tape",
  "Visual Comfort & Co.",
  "Vitamin A",
  "Vivienne Westwood",
  "Vogue Collection",
  "Vosges Haut-Chocolat",
  "VRG GRL",
  "Vyrao",
  "Warby Parker",
  "Waterford",
  "Watters",
  "WAYF",
  "We Norwegians",
  "Weezie",
  "West Elm",
  "Westman Atelier",
  "Weston Table",
  "Whit Jewelry",
  "Whiting & Davis",
  "Wilfred",
  "William Lockie",
  "Williams Sonoma",
  "With Nothing Underneath",
  "Wrangler",
  "YALI GLASS",
  "Yassmin Saleh",
  "Year & Day",
  "Yearly Co.",
  "Yellow the Label",
  "YETI",
  "YISE Beauty",
  "YSL Beauty",
  "Yves Salomon",
  "Z Supply",
  "Z.d.G",
  "Z.d.G.",
  "Zac Posen",
  "Zara",
  "Zara Home",
  "ZEGNA",
  "Zepplin the Label",
  "ZIIP",
  "Zimmerman",
  "ZIMMERMANN",
  "Zoe Lev",
];

export function normalizeBrandName(name: string): string {
  return name.trim().toLowerCase();
}

const ALLOWED_BRAND_NAME_SET: ReadonlySet<string> = new Set(
  ALLOWED_BRAND_NAMES.map(normalizeBrandName),
);

export function isAllowedBrandName(name: string | null | undefined): boolean {
  if (!name) return false;
  return ALLOWED_BRAND_NAME_SET.has(normalizeBrandName(name));
}

/**
 * Keeps only products whose *displayed* brand (`brands[0]`, the one shown on
 * the card/PDP) is on the allowlist.
 *
 * This is a belt-and-suspenders check on top of the `brand_ids` search
 * filter: Channel3 treats `brand_ids` as "matches ANY of the product's
 * brands", so a co-branded product (e.g. a collab tagged with both an
 * allowed and a disallowed brand) can pass that filter while still
 * *displaying* the disallowed brand first. Filtering on `brands[0]` here
 * catches that case regardless of which of the product's brands satisfied
 * the upstream filter.
 */
export function filterToAllowedDisplayBrand<T extends { brands?: readonly { name: string }[] | null }>(
  products: readonly T[],
): T[] {
  return products.filter((product) => isAllowedBrandName(product.brands?.[0]?.name));
}
